### ISSUE TITLE
add dataset loader a la MNE

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/hybrid-vocal-classifier#16]
https://github.com/mne-tools/mne-python/tree/master/mne/datasets

**Comment by agramfort** [comment]
the code you want to reuse is:

https://github.com/mne-tools/mne-python/blob/master/mne/utils.py#L1902

then put the file where you can. We put stuff in ~/mne_data

**Comment by NickleDave** [comment]
@agramfort that's very helpful, thank you

**Comment by agramfort** [comment]
your data would be a fun project for students :)

**Comment by NickleDave** [comment]
Added in commit cc366a4
