### ISSUE TITLE
Extract crashes when .cbin does not have associated .not.mat file 

### ISSUE THREAD

**Issue by senakoko** [NickleDave/hybrid-vocal-classifier#37]

**Comment by NickleDave** [comment]
Thanks @senakoko.
Fixed this with commit f0ef1af3767defd26666eb483723f1d0d15a2811.
I'll need to update the package on Anaconda cloud and you'll need to reinstall before it works for you. In the meantime the workaround of just putting .cbins without .not.mats in a subfolder should work.
