### ISSUE TITLE
Error using grid_search_svm_rbf

### ISSUE THREAD

**Issue by senakoko** [NickleDave/hybrid-vocal-classifier#39]
ValueError                                Traceback (most recent call last)
<ipython-input-33-1c223d05ccc2> in <module>()
----> 1 ans = hvc.utils.grid_search_svm_rbf(summ['features'],summ['labels'])

~\AppData\Local\Continuum\anaconda3\envs\hvc\lib\site-packages\hvc\utils\general.py in grid_search_svm_rbf(X, y, C_range, gamma_range)
    179     grid.fit(X, y)
    180     print("The best parameters are {} with a score of {0.2f}"
--> 181           .format(grid.best_params_, grid.best_score_))
    182     return grid.best_params_, grid.best_score_
    183

ValueError: cannot switch from automatic field numbering to manual field specification

**Comment by NickleDave** [comment]
fixed with 2edebab64395ec3c5fd5afe1d0c1b43794fd4d2e
thanks @senakoko
will push a new version to anaconda cloud in the next couple of days so you can update your install
