### ISSUE TITLE
Setting "predict_proba: True" for hvc.predict(..) script generates an Error message 

### ISSUE THREAD

**Issue by URSUroman** [NickleDave/hybrid-vocal-classifier#47]
Hello,

When executing hvc.predict(predict.yaml) with the parameter "predict_proba: True" in the todo_list, the terminal generates an Error(see below). Only when predict_proba is set to False can hvc.predict() execute normally.

Processing audio file 39 of 39.
predicting labels for features in file: features_from_032612_created_171204_1704
15
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\hvc\labelpredict.py"
, line 96, in predict
    pred_probs = clf.predict_proba(features_scaled)
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\sklearn\svm\base.py"
, line 590, in predict_proba
    self._check_proba()
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\sklearn\svm\base.py"
, line 557, in _check_proba
    raise AttributeError("predict_proba is not available when "
AttributeError: predict_proba is not available when  probability=False

Bellow I add the predict file (that generates the Error) for a better understanding:

predict: 
  todo_list:
    - 
      bird_ID: gy6or6
      model_meta_file : C:\Users\Roman admin\032612_out\select_output_171204_165440\svm_C1_gamma0.003\svm_200samples_replicate8.meta
      file_format: evtaf
      data_dirs:
        - C:\Users\Roman admin\032612
      output_dir: C:\Users\Roman admin\032612_out\
      **predict_proba: True**
      convert: notmat

Best regards,
Roman

**Comment by NickleDave** [comment]
Fixed by 9a751c166240e55ff1d83df695b5521a12cda3ac

**Comment by NickleDave** [comment]
Hey @URSUroman I uploaded a new version to Anaconda Cloud, testing it now. The new version fixes this issue with `predict_proba` and include the previous bug fix for SVM feature extraction.
