### ISSUE TITLE
hvc.extract throws `WinError 3: FileNotFound` when trying to make subdirectories

### ISSUE THREAD

**Issue by NickleDave** [NickleDave/hybrid-vocal-classifier#56]
need to change `os.mkdir` to `os.mkdirs`

**Comment by NickleDave** [comment]
@zbpvarun this function already uses `os.makedirs` so I think the source of the bug is a little more subtle.  
Can you paste the text of that config file into a comment field below? Thanks

**Comment by zbpvarun** [comment]
Code below:

extract:
  spect_params:
    ref: tachibana
  segment_params:
    threshold: 3000 # arbitrary units of amplitude
    min_syl_dur: 0.02 # ms
    min_silent_dur: 0.01 # ms

  todo_list:
    -
      bird_ID : pu63pu64
      file_format: evtaf
      feature_group:
        - svm
      data_dirs:
        - C:\DATA\Autolabeler_testing\pu63pu64\09202017_Day1
        - C:\DATA\Autolabeler_testing\pu63pu64\09242017_Day1

      output_dir: .

      labelset: ioplqweasdf

**Comment by NickleDave** [comment]
closing since the source of this bug is long lost to history
