### ISSUE TITLE
Bug with hvc.predict() for Koumura data format

### ISSUE THREAD

**Issue by URSUroman** [NickleDave/hybrid-vocal-classifier#65]
Hello,

I run hvc.extract() and hvc.select() on the attached data set in the Koumura format and it was ok.
When I run hvc.predict() on the same data set as for training (I use svm throughout), I get the following output on the terminal:

...
Processing audio file 19 of 21.
Processing audio file 20 of 21.
C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\hvc\audiofileIO.py:814: User
Warning: Segment 65 in 8.wav with label - not long enough for window function se
t with current spect_params.
spect will be set to nan.
  .format(ind, self.filename, label))
Processing audio file 21 of 21.
C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\hvc\audiofileIO.py:814: User
Warning: Segment 0 in 9.wav with label - not long enough for window function set
 with current spect_params.
spect will be set to nan.
  .format(ind, self.filename, label))
predicting labels for features in file: features_from_HVC_Koumura_short_created_
180220_173117
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\hvc\labelpredict.py"
, line 93, in predict
    features_scaled = scaler.transform(features)
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\sklearn\preprocessin
g\data.py", line 681, in transform
    estimator=self, dtype=FLOAT_DTYPES)
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\sklearn\utils\valida
tion.py", line 453, in check_array
    _assert_all_finite(array)
  File "C:\ProgramData\Anaconda3\envs\hvc\lib\site-packages\sklearn\utils\valida
tion.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
**ValueError**: Input contains NaN, infinity or a value too large for dtype('float64
').
>>>

I assume, the warnings are due to the fact that some segmented portions of the song are too short and are discarded which seems ok. However possibly while being discarded, some nan values are set somewhere which later generates an error and the prediction step doesn't work for me.

Best regards,
Roman 

[Annotation.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1740972/Annotation.zip)
[HVC_Koumura_short.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1740973/HVC_Koumura_short.zip)
[Koumura.extract.svm.config.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1740981/Koumura.extract.svm.config.zip)
[Koumura.select.svm2.config.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1740982/Koumura.select.svm2.config.zip)
[Koumura.predict.svm.config.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1740983/Koumura.predict.svm.config.zip)

**Comment by NickleDave** [comment]
Fixed by #66
