### ISSUE TITLE
scipy.signal.filtfilt() hangs when called by hvc.evfuncs.bandpass_filtfilt

### ISSUE THREAD

**Issue by URSUroman** [NickleDave/hybrid-vocal-classifier#68]
Hi David,

I installed the bleeding edge development version as described in: http://hybrid-vocal-classifier.readthedocs.io/en/latest/install.html#install.
While trying hvc.extract, select and predict on the data sets (in attached files), the extract and select steps are ok but the predict step hangs at proceszsing the first file:

>>> hvc.predict('Koumura.predict.svm.config.yml')
parsed predict config
Changing to data directory: C:\Users\Roman admin\Documents\SyllablesClassificati
on\Koumura Data Set\HVC_Koumura_short
Processing audio file 1 of 21.

The problem is that in function smooth_data -> bandpass_filtfilt (from file evfuncs.py) the function call scipy.signal.filtfilt() is not returning:
filtsong = scipy.signal.filtfilt(b, a, rawsong, padlen=padlen)

The values passed to filtfilt seem ok (a,b, rawsong) and since it is a library function I don't know how to debug it.

Roman
[Annotation.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1807153/Annotation.zip)
[HVC_Koumura_short.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1807154/HVC_Koumura_short.zip)
[Koumura.extract.svm.config.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1807155/Koumura.extract.svm.config.zip)
[Koumura.predict.svm.config.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1807156/Koumura.predict.svm.config.zip)
[Koumura.select.svm2.config.zip](https://github.com/NickleDave/hybrid-vocal-classifier/files/1807157/Koumura.select.svm2.config.zip)

**Comment by NickleDave** [comment]
Hey @URSUroman just letting you know I'm seeing this bug too.
In the middle of a major refactor of all the code but I will get to it because it's a fatal error for feature extraction.

Did you happen to notice if it's on a particular song file or not?

**Comment by URSUroman** [comment]
Hi David,

I tried to perform the training and prediction on different samples of song files.
Extraction and selection work well but prediction hangs at the filtfilt function in all cases. The problem with prediction doesn't seem to depend on a particular song file.

I also figured out that if I change the length of the vectors a and b in the filtfilt function, the function filtfilt returns. Specifically, if length(a) and length(b) are bellow ~28 the filtering returns but if the length is higher, the function filtfilt doesn't return.

**Comment by NickleDave** [comment]
wondering if this is because `evfuncs` gets called on Koumura data?

**Comment by URSUroman** [comment]
Hello David,
I don't remember exactly how this issue was solved but i think it was due to the format of the data. I apologize, i forgot to close the issue.
In scipy.signal.filtfilt(a,b,rawsong) rawsong has to be array_like, i think it should be (N,) like. Possibly I was feeding it with (N,1) like arrays and this is probably why it was hanging. Now it is working.

**Comment by NickleDave** [comment]
Hey @URSUroman hope you are well!
Wasn't expecting a reply.

Thank you for letting me know, I will close this

**Comment by NickleDave** [comment]
In case you're interested:
I just put together a final release and published it on PyPI so you can actually pip install. 
https://pypi.org/project/hybrid-vocal-classifier/
I made some fixes so it works with current versions of all the dependencies.

I saw you have a fork where it looks like you added some code to work with annotations?
You might find this tool useful:
https://github.com/NickleDave/crowsetta
I plan to integrate it into `hvc` shortly.
https://github.com/NickleDave/hybrid-vocal-classifier/issues/96

We need to run some experiments with a working version for paper revisions:
https://github.com/yardencsGitHub/tweetynet/issues/64
This is my (evolving) plan to get there
https://github.com/NickleDave/hybrid-vocal-classifier/projects/1

Please let me know if I'm doing anything that affects you.
Also would be happy to chat at some point and hear your feedback on working with the library.
I really appreciate the input you have given me.

**Comment by URSUroman** [comment]
Thank you very much David for the links especially for crowsetta. 
We can off course discuss about the tool: 
It is very helpful to us, thank you for having developed it. 
I was however wondering if a user wants to use the svm algorithm for the classification, is there a documentation on how to choose the hyperparameters C and gamma in the Select.yml file? The default parameters worked for me but i wonder if it will always be the case for the users. 


De: "David Nicholson" ***@***.***> 
À: "NickleDave/hybrid-vocal-classifier" ***@***.***> 
Cc: "Roman Ursu" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Dimanche 11 Avril 2021 16:36:48 
Objet: Re: [NickleDave/hybrid-vocal-classifier] scipy.signal.filtfilt() hangs when called by hvc.evfuncs.bandpass_filtfilt (#68) 





In case you're interested: 
I just put together a final release and published it on PyPI so you can actually pip install. 
[ https://pypi.org/project/hybrid-vocal-classifier/ | https://pypi.org/project/hybrid-vocal-classifier/ ] 
I made some fixes so it works with current versions of all the dependencies. 

I saw you have a fork where it looks like you added some code to work with annotations? 
You might find this tool useful: 
[ https://github.com/NickleDave/crowsetta | https://github.com/NickleDave/crowsetta ] 
I plan to integrate it into hvc shortly. 
[ https://github.com/NickleDave/hybrid-vocal-classifier/issues/96 | #96 ] 


We need to run some experiments with a working version for paper revisions: 
[ https://github.com/yardencsGitHub/tweetynet/issues/64 | yardencsGitHub/tweetynet#64 ] 
This is my (evolving) plan to get there 
[ https://github.com/NickleDave/hybrid-vocal-classifier/projects/1 | https://github.com/NickleDave/hybrid-vocal-classifier/projects/1 ] 


Please let me know if I'm doing anything that affects you. 
Also would be happy to chat at some point and hear your feedback on working with the library. 
I really appreciate the input you have given me.

**Comment by NickleDave** [comment]
> I was however wondering if a user wants to use the svm algorithm for the classification, is there a documentation on how to choose the hyperparameters C and gamma in the Select.yml file? The default parameters worked for me but i wonder if it will always be the case for the users.

sorry for the delayed reply -- this is a good point @URSUroman thank you, I will raise an issue to add it to the docs
